### ISSUE TITLE
code from samples doesn't include failure assertions

### ISSUE THREAD

**Issue by olevett** [andrewabest/Conventional.Samples#1]
Lifting straight from the examples leads to tests that always pass, as they're lacking 
```
.WithFailureAssertion(Assert.Fail);
```

This is set up in the TestSetup, but I'm not sure it's that obvious - I'm happy to put in a PR for this if it's useful, but it looks like the samples aren't the most up to date anyway so if there's something more useful I can do let me know :)

**Comment by andrewabest** [comment]
Hi @olevett!

That's a great point. Perhaps in this case it might be more sensible to have the failure assertions inline to create a better 'pit of success' for people?

The samples were created a while back - they should really be updated to the latest version of Conventional (v6) at the very least, and probably update to new csproj / dotnet core as well.

Did you want to have a go at updating the conventional dependency and inlining the failures? If so I can tackle the dotnet core upgrade afterwards.

**Comment by olevett** [comment]
I think that seems reasonable, after trying copy/paste I did find the docs that point you down the path (and appreciate that for example the doomsday checks need the globally assigned assertions).

Will spin out some PRs for those bits, might be a couple of days before I get a chance though.

**Comment by olevett** [comment]
I've raised a couple of PRs for the above. I'm also happy to have a stab at the dotnet core upgrade if that's useful.

I think there'll need to be a couple of changes in MediatR (targeting a version that's more recent, which I think changes some of the async behaviour) but otherwise shouldn't be too major.

**Comment by andrewabest** [comment]
Resolved with #2 and #3 - thanks once again @olevett!

**Comment by andrewabest** [comment]
I've updated the samples to dotnet core 3, so our work here is done :shipit:
